canonical/core-initrd

.gitignore
spread.yaml
tests/bin/MATCH
tests/bin/REBOOT
tests/lib/nested.sh
tests/lib/prepare-uc20.sh
tests/lib/repack-kernel.sh
tests/spread/basic/task.yaml

This sets up the project to be testable via spread, both locally via nested QEMU
VM's, as well as in the cloud with GCE nested VM's.
There are some TODO's still around simplifying this even more and getting rid of
more cruft from snapd's setup, but this is sufficient right now to get a nested
UC20 VM with our version of the initramfs in it for testing.
To run the tests locally via qemu, first install qemu, then get spread via 
```
$ sudo apt update && sudo apt install -y qemu-kvm autopkgtest
$ curl https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz | tar -xz -C $GOPATH/bin
```
Then make your qemu spread images dir with
```
$ mkdir -p ~/.spread/qemu
$ cd ~/.spread/qemu
```
and make a suitable spread image with:
```
$ autopkgtest-buildvm-ubuntu-cloud -r focal
$ mv …
```

many: add spread testing using GCE backend for ubuntu-core-initramfs

---

debian/rules

This makes it much easier to tell what version of snap-bootstrap was included in
the initramfs when bugs, etc. happen and we need to figure out what version of
snap-bootstrap is running in the initramfs.

debian/rules: also install snapd info file

---

factory/usr/lib/systemd/system/initrd-cleanup.service.d/core-override.conf
factory/usr/lib/systemd/system/initrd-root-device.target.d/40-seed-device.conf
factory/usr/lib/systemd/system/initrd-root-fs.target.d/40-seed-device.conf
factory/usr/lib/systemd/system/populate-writable.service
factory/usr/lib/systemd/system/run-mnt-ubuntu\x2dseed.mount.d/override.conf
factory/usr/lib/systemd/system/the-tool.service
factory/usr/lib/the-modeenv
factory/usr/lib/the-tool

* Delete manual references to ubuntu-seed fsck jobs, these are manually created
by snap-bootstrap now
* Delete the handling around snap-bootstrap output and instead just invoke 
snap-bootstrap directly
* Add TODO's around additional things we want to move to snap-bootstrap 
eventually
* Switch back to isolating to initrd.target so we don't have leftover units and
unfreed memory from the initrd now that all mounts from snap-bootstrap 
properly persist across the pivot_root.
* Make the-tool depend on systemd-udev-settle so that all /dev device nodes are
populated when we run snap-bootstrap.
* Remove hackish ubuntu-boot mount entry being injected into the fstab from
the-modeenv now that snap-bootstrap correctly sets up the mounts.
This completes the work for UC20 1.0 release (minus other …

many: update initramfs layout for new snap-bootstrap features

---

factory/usr/lib/systemd/system/the-tool.service

This is important for field debugging where we want to be able to see why
"the-tool" failed.

the-tool: log stdout, stderr to journal and console

---

factory/usr/lib/the-modeenv

This commit ensures the ESP efi dir is available for firmware
update tooling. This fixes LP: 1892392

the-modeenv: bind mount /boot/efi -> /run/mnt/ubuntu-seed

---

.github/workflows/tests.yml

This PR does not include #20, so let's see if using checkout v2 causes us to use the merge commit for tests

.github/workflows/tests.yml: use checkout v2

---

factory/usr/lib/systemd/system/initrd-switch-root.service.d/core-override.conf

This is the result of my goose-chase why `systemd-analyze time` does not
break out the time spend in initrd. It turns out that for this to work
systemd needs to re-exec statefully. But because of issues with systemd
and/or the way we use it this can't be done right now. So to ensures
that this knowledge is preserved I added some more comments to the
relevant override.
Thanks to Dimitri for (patiently) explaining all this.

initrd-switch-root.service.d: provide a bit more context

---

debian/control

git is currently needed to build the core-initrd so it should be
part of the build-depends. Without that e.g. `spread qemu-nested:`
fails early.
Thanks for Sertac for spotting this.

debian: add git to build-depends

---

debian/rules

This commit explains how the forked snapd repo for the "cloudimg-rootfs"
feature is used.
Thanks to Dimitri for explaining this patiently.

debian: explain how forked snapd repo is used

---

spread.yaml
tests/lib/nested.sh

There are currently a bunch of spread failures. It looks like they
might be related to the fact that the test take a long time. This
is also evident from seeing some "green" runs. This commit increases
the timeouts to have more consistent results.

spread: increase timeouts and fixes

---

debian/rules

The branch it is based on is WIP, so better fix it to something we
know is working, for the moment.

debian: pin to commit when building snap-bootstrap

---

README.md
factory/usr/lib/systemd/system/initrd-switch-root.target.wants/systemd-bootchart-quit.service
factory/usr/lib/systemd/system/sysinit.target.wants/systemd-bootchart.service
factory/usr/lib/systemd/system/systemd-bootchart-quit.service
factory/usr/lib/systemd/system/systemd-bootchart.service

Previously, we started systemd-bootchart by adding
rd.systemd.wants=systemd-bootchart.service to the kernel command
line. This has as a side effect that the service is added to the
initrd default target and is started later than desired. Instead,
enable the service by default and use a new kernel command line
parameter (core.bootchart) as condition to start it. We also need to
make sure that the service is stopped properly to the bootchart is
written to the /run folder.

Start bootchart earlier

---

debian/changelog

There is new snapd in snappy-dev/image ppa, and core-initrd rebuild has been requested to include that.

releasing package ubuntu-core-initramfs version 51

---

factory/usr/lib/systemd/system/the-tool.service

sysinit.target already runs after systemd-tmpfiles-setup.service,
systemd-modules-load.service, and systemd-udev-settle.service.
We also explicitly put the-tool.service in initrd-root-device.target,
because it is a dependency of initrd-fs.target but does not need to
stay alive through the switch root.
initrd.target already wants sysinit.target (through basic.target) so
we do not need to add a "Wants". It also helps not to not inject an
indirect "Wants" from initrd-fs.target to sysinit.target which we do
not want, since all the services from sysinit.target have to be re-run
in main, thus need to be taken down in switch root.
This is extracted from #59

Simplify dependencies of the-tool.service

---

factory/usr/lib/systemd/system/initrd-switch-root.target.wants/snapd.recovery-chooser-trigger.service
factory/usr/lib/systemd/system/snapd.recovery-chooser-trigger.service.d/survive-switch-root.conf

`snap-bootstrap recovery-chooser-trigger` is only expected to use
`/run` so it can safely survive the switch root.
When using stateful re-execution of systemd, this will keep the same
service started from initramfs and continue into the main boot.
Because we need to pull it into `initrd-switch-root.target`, we also
need to remove default dependencies so that we do not indirectly pull
`sysinit.target` or `local-fs.target` into
`initrd-switch-root.target`.
Note, we should probably add a signal handler in `snap-bootstrap
recovery-chooser-trigger` to be notified when `initrd-root-fs.target`
is reached to `chdir` into `/sysroot` so that we do not drag the old
initramfs in memory until it is stopped. This is because systemd will
lazily umount the old root.

recovery-chooser-trigger.service: Survive the switch root

---

factory/usr/lib/systemd/system/tmp.mount.d/umount.conf

This is a follow-up to #58. It will be unmarked as draft once #58 is merged.
Otherwise with stateful re-execution, systemd will think for a short
time that it is mounted. It will start `systemd-tmpfiles-setup` and
`systemd-timesyncd` too early.

Make sure tmp.mount is stopped before switch

---

factory/usr/lib/udev/rules.d/56-persist-device-mapper.rules

55-dm.rules will disable cold plugged device mapper block devices.  In
order for it not to disable them we need to keep the state from initrd
to main boot. That is we need to mark the devices as `persist_db` so
that initrd-udevadm-cleanup-db.service does not remove it.
When a device mapper device gets disabled, then all systemd mounts
with BindsTo to the device will get unmounted, as well as all bind
mounts that depend on it. Which causes a catastrophic failure of
Ubuntu Core.
As a work-around for this issue we have used a stateless reexecution
of systemd. This was making systemd forget about encrypted mount units
and thus did not trigger unmount when devices were taken down.
Now that we mark the device mapper devices as `persist_db`, this
work-around is not needed anymore.
Tested on:
- …

Persist device mapper devices in udev database

---

bin/ubuntu-core-initramfs

Currently server feature is only enabled by default on x86_64
architecture. Also enable server feature for generic kernels, as they
are likely to boot in Qemu too.
BugLink: https://bugs.launchpad.net/bugs/1938530
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@canonical.com>

features: enabled server feature on x86_64 and any generic kernels.

---

debian/rules
factory/usr/lib/systemd/system/tmp.mount.d/umount.conf

/tmp is not useful in initrd for any of its service. It also requires
some hack to unmount properly. It is better to get rid of it.

Remove tmp.mount

---

factory/usr/lib/the-modeenv

Mount piboot from seed if the piboot bootloader is being used. Depends on https://github.com/snapcore/core-base/pull/30.
Leaving as draft for the moment - we can decide to merge it or not depending on how quickly https://github.com/snapcore/core-base/pull/25 is merged.

the-modeenv: mount piboot from seed if present

---

bin/ubuntu-core-initramfs
debian/control

We switch to llvm-objcopy to be able to build kernel.efi for arm64 and
other non-x86 architectures in the future.

Switch to using llvm-objcopy instead of objcopy to create kernel.efi

---

bin/ubuntu-core-initramfs
debian/control

UC22 kernels support zstd compressed initramfs, and after extensive
analysis the default compression on classic was changed to zstd -1 -T0
(see ubuntu-devel threads and analysis from waveform). This
compression method improves compression ratio, compression speed, as
well as reduces decompression memory required.
Further improvements can be achieved later with firmware and module
compression.

Switch from lz4 to zstd compression

---

bin/ubuntu-core-initramfs
debian/install
modules/main/extra-modules.conf

Previously, the only way to include kernel modules in the initramfs
was to add them to files in factory/usr/lib/modules-load.d/, which
forces the modules to be loaded. Use now per-feature configuration
files so we can include the modules without forcing their loading.
Use this feature to include the dwc2 driver for linux-raspi kernel.
On 5.15 kernel (jammy), this module needs to be included in the
initramfs to have proper USB support at that stage. One side effect of
not having this was that the ethernet driver got loaded later than in
previous releases.

many: add folder with files specifying kernel modules for initramfs

---

factory/usr/lib/modules-load.d/ubuntu-core-initramfs.conf
factory/usr/lib/recovery-chooser-trigger-switch-root
factory/usr/lib/systemd/system/initrd-switch-root.target.wants/recovery-chooser-trigger-switchroot.service
factory/usr/lib/systemd/system/recovery-chooser-trigger-switchroot.service
modules/main/extra-modules.conf

We need to chroot when switching root, so we send SIGUSR1 to recovery
chooser trigger.
We need to load all hid drivers. We should not load them into the
kernel though.
This works with https://github.com/snapcore/snapd/pull/11742

Fix recovery chooser trigger on NUC

---

debian/rules

oomd is probably not needed during initramfs:
- `etc/systemd/oomd.conf`
- `usr/bin/oomctl`
- `usr/lib/systemd/system/systemd-oomd.service`
- `usr/lib/systemd/systemd-oomd`
- `usr/share/dbus-1/system-services/org.freedesktop.oom1.service`
- `usr/share/dbus-1/system.d/org.freedesktop.oom1.conf`
Those files are related to containers:
- `usr/bin/systemd-dissect`
- `usr/lib/systemd/system/systemd-nspawn@.service`
The following files are not distributed in Ubuntu:
- `usr/lib/systemd/system/systemd-hwdb-update.service`
- `usr/lib/systemd/system/systemd-journal-catalog-update.service`
- `usr/lib/systemd/system/systemd-update-done.service`
- `usr/lib/systemd/systemd-update-done`
- `usr/lib/tmpfiles.d/etc.conf`

debian/rules: Remove more unused systemd files

---

debian/changelog

Upload ubuntu-core-initramfs with cloudimg-rootfs feature fixedup

releasing package ubuntu-core-initramfs version 57

---

factory/usr/lib/systemd/system-generators/journald-console
factory/usr/lib/the-modeenv
factory/usr/libexec/core/get-arg

Also:
Parse /proc/cmdline correctly
There is potential quotes in kernel command line and we need to handle those correctly.
For more information on how to parse kernel parameters, see function `next_arg` in https://github.com/torvalds/linux/blob/master/lib/cmdline.c

Do not forward journal to console when quiet

---

debian/rules
factory/usr/lib/systemd/system/basic.target.wants/populate-writable.service

Break cycle introduced in #102 with plymouth and systemd-password. It was discovered in https://github.com/snapcore/core-initrd/pull/102#issuecomment-1222297471 but was not properly fixed.
Also remove `populate-writable.service` from `basic.target`. It is not needed.

Fix unit dependencies

---

modules/main/extra-modules.conf

So we can have splash with intel GPUs.

modules: include intel drm in initramfs

---

debian/rules

snap-bootstrap CVM feature got merged into next snapd release.
This can be merged, once CVM capable snap-boootstrap / snapd.deb lands in the snappy-dev ppa for jammy.

debian/rules: drop cloudimg-rootfs forked snap-bootstrap

---

debian/rules
factory/usr/lib/systemd/system-generators/kernel-snap-generator

This generator should also be run in classic root. That means should be later moved into a package and installed on classic, and core-initrd should copy from there.

Add generator for kernel mount points on classic

---

tests/lib/prepare-uc.sh
tests/lib/prepare-utils.sh
tests/spread/ci/task.yaml
vendor/systemd/.github/workflows/build_test.sh

Lately CI was failing because of some problem with configuration of openssh-server.

tests: avoid interactions when using apt

---

bin/ubuntu-core-initramfs

When having a module both in extra-modules.conf and in a file in main/usr/lib/modules-load.d/, "ubuntu-core-initramfs create-initrd" crashed because of a wrong value check in the script. This commit fixes that.
Reported in https://github.com/snapcore/core-initrd/issues/134

bin/ubuntu-core-initramfs: fix ubuntu-core-initramfs crash

---

debian/control

The better way to enable riscv64 builds than what was proposed in https://github.com/snapcore/core-initrd/pull/140
With full EFI support as well.

Enable riscv64 build

---

debian/rules

An upcoming systemd sru will introduce additional (future) naming schemes, to ensure backwards compatibility explicitly configure systemd networkd udevd net-naming-scheme to remain the same, at v245, as before.
See related LP & focal classic SRU.

vendor/systemd: maintain stable default net-naming-scheme

---

modules/server/extra-modules.conf

These modules are for qemu support, and are especially useful for arm64.

Add GPU and input virtio modules

---

debian/control

See:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023363 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023442
python3-pyparsing switched from Multi-Arch: no to Multi-Arch: foreign in most recent releses. To continue cross-building, the build-dependency must change from python3-pyparsing:native to an arch-unqualified name. Use alternative specification to allow building existing core-initrd on either jammy or lunar, simultaniously. This should unbreak the recipe build.

Fix python3-pyparsing build-depends

---

bin/ubuntu-core-initramfs
postinst.d/ubuntu-core-initramfs

As part of automating and producing more kernel snaps for more targets, it is desired to auto-generate kernel.efi as unsigned, and world-readable. Neither unsigned or snakeoil kernel.efi are ever installed on end user systems, and this .deb packaging hook is only used as part of kernel team's build processes.
Also add support for arm64, as we do produce many EFI arm64 snaps already, which use more complicated packaging, because of this missing create-efi call.

Adapt maintainer scripts for ease of snap automation

---

tests/lib/prepare-utils.sh

CI is failing when upgrading grub.

spread: disable apt upgrade of grub-efi-amd64-signed

---

debian/control
debian/rules
factory/usr/lib/systemd/system/snap-initramfs-mounts.service

D-Bus system bus is needed by `systemd-run --wait`.

Add dbus system bus

---

debian/changelog
debian/control

add build-conflicts on the snap-bootstrap version that has caused a recent regression. This is a safety precaution to prevent a future missbuilt.
also set a correct, SRU style version number for jammy builds going forward.

core22: Add build-conflicts on snapd 2.59.3

---

bin/ubuntu-core-initramfs
postinst.d/ubuntu-core-initramfs

cherry-pick fix from main to ease building & signing kernel.efi snaps

core22: fix hook permissions

---

bin/ubuntu-core-initramfs
postinst.d/ubuntu-core-initramfs

cherry-pick fix from main to ease building & signing kernel.efi snaps

core20: fix hook permissions

---

bin/ubuntu-core-initramfs
debian/control
debian/rules

Include snap-bootstrap and other files from snapd package when the ubuntu-core-initramfs script is run, instead of when the ubuntu-core-initramfs package is created. So now snapd is a run dependency instead of a build dependency.

bin,debian: include snapd bits from the run system

---

debian/rules

U-boot needs to save `boot.sel` back to the boot partition. Because ext4 is not safe to write on some U-Boot builds due to journal corruption, we need to allow the gadget to create the boot partition as a vfat. Which means `mkfs.vfat` is required during installation.

Add mkfs.vfat for u-boot gadgets

---

debian/control
debian/rules
factory/usr/lib/systemd/system/the-tool.service

D-Bus system bus is needed by `systemd-run --wait`.
Backport of #153

[core20] Add dbus system bus

---

debian/control
debian/rules
factory/usr/lib/systemd/system/snap-initramfs-mounts.service

D-Bus system bus is needed by `systemd-run --wait`.
Backport of #153

[core22] Add dbus system bus

---

debian/control

Otherwise ubuntu-core-initramfs FTBFS in mantic.
Fixes: https://github.com/snapcore/core-initrd/pull/180

Add fdisk build-depends for /sbin/sfdisk vendor

---

README.md
factory/usr/lib/systemd/system/systemd-bootchart-quit.service
factory/usr/lib/systemd/system/systemd-bootchart.service

in the kernel command line, instead of core.bootchart.

Trigger bootchart if ubuntu_core.bootchart is set

---

README.md
factory/usr/lib/systemd/system/systemd-bootchart-quit.service
factory/usr/lib/systemd/system/systemd-bootchart.service

To keep consistency with other kernel command line settings.

Accept ubuntu_core.bootchart as alias for core.bootchart

---

postinst.d/ubuntu-core-initramfs

Also see https://github.com/canonical/nullboot/issues/53
Previously kernel.efi for azure passed in cmdline argument, but I'm now trying to standardtize creation of all kernel.efi, thus it would be best to move this change here for now.

main: Nullboot doesn't seal cmdline yet, thus it must be baked in.

---

postinst.d/ubuntu-core-initramfs

Also see https://github.com/canonical/nullboot/issues/53
Previously kernel.efi for azure passed in cmdline argument, but I'm now trying to standardtize creation of all kernel.efi, thus it would be best to move this change here for now.
Pull request for main is at https://github.com/snapcore/core-initrd/pull/194

core22: Nullboot doesn't seal cmdline yet, thus it must be baked in.

---

factory/usr/lib/systemd/system/classic-mounts.service
factory/usr/lib/systemd/system/detect-classic-sysroot.service
tests/lib/prepare-utils.sh

On mantic, systemd has changed behavior and it does not run daemon-reload from the initrd-parse-etc service if there is nothing that specifically needs that in /etc/fstab, so we were not running kernel-snap-generator again at this point, which meant we did not mount /lib/{modules,firmware} on classic systems. To fix that, force re-running the generators from a service that runs after we have the needed mountpoints.
With this kernel modules can be loaded again and snapd.seeded can progress on classic systems.

factory: create mount units specific to classic

---

factory/usr/lib/udev/rules.d/56-persist-device-mapper.rules

Note that while we do not plan to bring systemd re-exec in UC20, this fix does fix the state of dev mapper devices. Without this fix, they are disabled with `SYSTEMD_READY=0` while being dependencies of inferred mount units, which can be problematic in some cases.
The following is the commit message:
55-dm.rules will disable cold plugged device mapper block devices.  In order for it not to disable them we need to keep the state from initrd to main boot. That is we need to mark the devices as `persist_db` so that initrd-udevadm-cleanup-db.service does not remove it.
When a device mapper device gets disabled, then all systemd mounts with BindsTo to the device will get unmounted, as well as all bind mounts that depend on it. Which causes a catastrophic failure of Ubuntu Core.
As a …

[backport] Persist device mapper devices in udev database

---

bin/ubuntu-core-initramfs
debian/changelog

This removes requirement to gzip decompress kernels before creating kernel.efi on arm.

core22: On arm64, attempt to decompress vmlinuz automatically.

---

bin/ubuntu-core-initramfs
debian/rules

this will simplify a lot of things packaging side.
But also might switch to zimg soon anyway.

main: On arm64, attempt to decompress vmlinuz automatically.

---

modules/main/extra-modules.conf

These drivers are required for USB HOST for mt8195-demo board. 
mt6360_charger
mtk-pmic-wrap
nvmem_mtk-efuse
https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/2038512

modules/main: enable USB HOST support for MediaTek mt8195-demo platform.

---

bin/ubuntu-core-initramfs

Now modules are compressed and have extension .ko.zstd. We need to ignore the compression extension. 
The module database was not properly generated, and was causing spurious error messages. (That database is only to find errors).

ubuntu-core-initramfs: Fix discovery of compressed modules

---

bin/ubuntu-core-initramfs

This file is needed by dracut-install when installing modules. So we should copy it.

ubuntu-core-initramfs: copy missing modules.builtin.modinfo

---

bin/ubuntu-core-initramfs

In Noble, systemd package files moved from /lib to /usr/lib, account for that.

bin/ubuntu-core-initramfs: Fix systemd package file paths

---

debian/changelog

So versions of automatic builds are more modern in noble than in jammy.

Update changelog version

---

bin/ubuntu-core-initramfs
factory/usr/lib/systemd/system/sysroot-usr-lib-firmware.mount.d/what.conf
factory/usr/lib/systemd/system/sysroot-usr-lib-modules.mount.d/what.conf

The kernel will call specifically path `/sbin/modprobe`. So we need to make sure this path exists and points to modprobe.

ubuntu-core-initramfs: fix path to /sbin/modprobe

---

bin/ubuntu-core-initramfs

bin/ubuntu-core-initramfs: make sure the initramfs can be cross-built

---

bin/ubuntu-core-initramfs
debian/changelog

Create manifest when running "ubuntu-core-initramfs create-initrd" with debian packages and package repositories used to build the initramfs. This file will be found in path /usr/share/doc/dpkg.yaml.

bin/ubuntu-core-initramfs: create manifest with used packages

---

.github/workflows/tests.yaml
factory/usr/lib/core/extra-paths
factory/usr/lib/systemd/system-generators/kernel-snap-generator
tests/lib/prepare-utils.sh
tests/spread/build/build-initrd/task.yaml

Do not mount /lib/{modules,firmware} in case snapd created a drivers
tree for our kernel snap, as in that case these mounts will be created
by snapd-generator from the base or from the snapd deb package for
hybrid systems. This situation is expected to happen only for UC24+.

factory: do not mount /lib/{modules,firmware} if there is a drivers tree

---

modules/main/extra-modules.conf
modules/server/extra-modules.conf

This will allow mounting partitions with dm-verity in the initrd as well as overlayfs mounts.

modules/main/extra-modules.conf: enable dm_verity and overlay modules

---

bin/ubuntu-core-initramfs

ldconfig assumes /etc exists and fails otherwise. This issue started to happen on oracular because in the past previous steps already created /etc.

bin/ubuntu-core-initramfs: create /etc for ldconfig

---

factory/usr/lib/systemd/system/classic-mounts.service

Add RemainAfterExit=yes to classic-mounts.service unit to make sure it is considered active by systemd. Otherwise, it was started twice in the initramfs, and in the second run there was a race condition with initrd-udevadm-cleanup-db.service, where if daemon-reload happened after cleaning the udev database, systemd considered some device units unplugged, including disks, which in turn led to unmounts in /run/mnt. In turn this was causing that /lib/{modules,firmware} was not being mounted after switch root.

factory: make classic-mounts.service active after finishing

---

vendor/systemd-patches/0074-relocate-kernel-image-to-allocate-space-for-BSS.patch

The kernel image needs to be relocated in order to allocate enough space for the BSS. If no space is reserved for the BSS, it can overlap with the initrd in memory, causing the corruption of it.
This change uses a similar approach as taken by upsteam in:
https://github.com/systemd/systemd/pull/33882
https://github.com/systemd/systemd/issues/33816
And fixed by systemd upstream commit id 19812661f1f6 ("stub: allocate and zero enough space in legacy x86 handover protocol").
However since the base code was vastly different, this patch basically replicates the same relocation strategy used by ARM in "vendor/systemd/src/boot/efi/linux.c".
The code could have been refactored to share code with ARM, but to minimize the risk of regressions to other architectures, linux.c was left untouched.

EFI stub: Relocate kernel image to allocate space for BSS

---

factory/usr/lib/core/extra-paths

These files are generated by snap-bootstrap when booting a hybrid system into recovery mode. The files contain a combination of the login information from the hybrid rootfs and the base.

factory: mount users imported from hybrid system during recovery mode

---

bin/ubuntu-core-initramfs
debian/control

Now systemd loads most of libraries through dlopen. It also defines a .notes.dlopen section to ELF binaries to list those libraries.  We use `dlopen-notes` to list those dependencies and warn about missing ones. And eventually fail for required ones.

bin/ubuntu-core-initramfs: warn about missing dynamic dependencies

---

bin/ubuntu-core-initramfs

snap-bootstrap needs to call /sbin/reboot in recover mode when remodeling.

bin/ubuntu-core-initramfs: add /sbin/reboot symlink
